### ISSUE TITLE
NAMAページのUIコピー

### ISSUE THREAD

**Issue by YuyaImanari** [YuyaImanari/2020nama#1]
**やること**

期限：3/31

- [ ] headタグを書く
- [ ] bodyタグを書く

**Comment by chisaakiyama** [comment]
css追加しました。

**Comment by chisaakiyama** [comment]
linkとかよくわかりませんでした。
何か残そうと思ってbodyのNAMAとはについてだけかきました。

**Comment by chisaakiyama** [comment]
CSS設定はできたと思います、、

**Comment by chisaakiyama** [comment]
htmlにNAMAチームから送られてきた「記載する情報」をすべてかきました。

**Comment by chisaakiyama** [comment]
片日→どちらか1日
言葉を訂正しました。

**Comment by chisaakiyama** [comment]
cssで主に文字の設定をしました。

**Comment by chisaakiyama** [comment]
PRIZE部分のCSSを一部やりました。

**Comment by chisaakiyama** [comment]
背景の色、ボーダーをやりました。文字の大きさが上手く反映していない気がします。。

**Comment by chisaakiyama** [comment]
前回の背景の色・ボーダーを細かく設定しました。
・画像が上手く反映されない。
・<dt>を使用している部分で一緒に反映されてしまう。

**Comment by chisaakiyama** [comment]
headのSNS設定しました。

**Comment by chisaakiyama** [comment]
スケジュールの初めの赤い部分をしました

**Comment by chisaakiyama** [comment]
解禁画像を入れました。
スケジュールの赤い部分を中央にしました。

**Comment by chisaakiyama** [comment]
最初の部分の文字の大きさ、太さを変えました。

**Comment by chisaakiyama** [comment]
解禁画像を変えようとしたけど、上手くできませんでした。

**Comment by chisaakiyama** [comment]
パソコン版とスマホ版で
・解禁画像
・スケジュールの赤い部分
大きさ変更しました。

スマホ版での文字の並びを訂正しました。

**Comment by YuyaImanari** [comment]
**修正依頼**
- [x] (細かいことだけど)トップの画像(h1のimg)の max-width: 1440px; にする
- [x] class="section-wrap" にもmax-widthを設定する
- [ ] class="schedule-list-time__inner" 内の spanタグ のfont-sizeいい感じにする
- [x] class="sns-btn-wrapper" 内の aタグ の下線が見えてるから、text-decoration: none; を指定して消す
- [ ] class="entry-outline-detail"内の ddタグ のmargin-leftが不自然。パソコン版もスマホ版も、class="section-wrap"のwidthの修正後に検討してみて！

長々と失礼。チェックボックスになってるから使ってください。

**Comment by chisaakiyama** [comment]
修正依頼のうち３つを直しました。
class="schedule-list-time__inner"のfont-sizeは３行に改行したいので、その後調整します。

**Comment by chisaakiyama** [comment]
間隔とか行の頭の細かいところを調整しました。

**Comment by chisaakiyama** [comment]
パソコン版はきれいになりましたが、スマホ版が崩れました。

**Comment by chisaakiyama** [comment]
できました！
